### PR TITLE
Fix #4609: Error on downscale command

### LINKED ISSUE #4609: Error on Downscale
### What steps will reproduce the problem?

Upload a corrupt image and run downscale command.

### What is the expected result?

Skip file

### What do you get instead?

Next Imagine\Exception\RuntimeException: Unable to open image /xxx/41c1-a4b3-1882d886d876/file in /srv/humhub/protected/vendor/imagine/imagine/lib/Imagine/Imagick/Imagine.php:57
Stack trace:
#0 /srv/humhub/protected/humhub/modules/file/libs/ImageHelper.php(108): Imagine\Imagick\Imagine->open('/srv/www/htdocs...')
#1 /srv/humhub/protected/humhub/modules/file/commands/FileController.php(89): humhub\modules\file\libs\ImageHelper::downscaleImage(Object(humhub\modules\file\models\File))
#2 [internal function]: humhub\modules\file\commands\FileController->actionDownscaleImages()
#3 /srv/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Arra

### Additional info

| Q                | A
| ---------------- | ---
| HumHub version   | 1.7
| PHP version      | 
| Operating system |

> Note: Also provide the full error stacks from `Administration --> Information --> Logging` and errors from your browser console if possible.
> Note: Please use the [community](https://community.humhub.com) site for any questions on customizing HumHub.

### PR DESCRIPTION
**Pull request by luke-**
**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: protected/humhub/config/common.php [hunk 1]
```diff
@@ -24,7 +24,7 @@
 
 $config = [
     'name' => 'HumHub',
-    'version' => '1.7.0',
+    'version' => '1.8.0-dev',
```
Comment (buddh4) [inline protected/humhub/config/common.php:27]: Its currently a master PR?

Comment (luke-) [reply protected/humhub/config/common.php]: Good catch, had the wrong base branch
