### PR TITLE
Fix #4555: Default password validation error message missing translat…

### LINKED ISSUE #4555: Default password strength weaker than intended or wrongly commented
The defaultPasswordStrength is set to a minimum of 5 characters but the comment says 8.

https://github.com/humhub/humhub/blob/4e1ef6b060c1dcc4d244c8664f27706277683183/protected/humhub/modules/user/Module.php#L118

### PR DESCRIPTION
**Pull request by luke-**
…ion and wrong min. characters

**What kind of change does this PR introduce?** (check at least one)

- [X] Bugfix
- [ ] Feature
- [ ] Code style update
- [ ] Refactor
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [ ] No

If yes, please describe the impact and migration path for existing applications:

**The PR fulfills these requirements:**

- [ ] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [ ] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests are passing
- [ ] New/updated tests are included
- [ ] Changelog was modified

If adding a **new feature**, the PR's description includes:
- [ ] A convincing reason for adding this feature (to avoid wasting your time, it's best to open a suggestion issue first and wait for approval before working on it)

**Other information:**

### CODE REVIEW

File: protected/humhub/modules/user/models/Password.php [hunk 1]
```diff
@@ -198,7 +198,7 @@ private function validateAdvancedPasswordRules($attribute, $params)
             foreach ($additionalRules as $pattern => $message) {
                 $errorMessage = $userModule->isCustomPasswordStrength() ?
                     Yii::t('UserModule.custom', $message) :
```
Comment (buddh4) [inline protected/humhub/modules/user/models/Password.php:200]: Is this an up to date solution for custom translations? Still not sure whats the suggested approach or translation category for custom user messages.

**Review by buddh4 — APPROVED** [review]

File: protected/humhub/modules/user/models/Password.php (hunk 1 above)
Comment (luke-) [reply protected/humhub/modules/user/models/Password.php:200]: The Translation Manager newly module supports database sources e.g. for profile pields but no support manual config strings.
