### PR TITLE
Fix: polymorphic relation lookup (Fix #6772)

### LINKED ISSUE #6772: Humhub 1.16.0 - Error with `PolymorphicRelation::getPolymorphicRelation()`
### What steps will reproduce the problem?

I cannot tell, but on my Humhub instance, it occurred when viewing the notification list.

The problem is that `$this->owner->getAttribute()` can return null:
https://github.com/humhub/humhub/blob/1db793da1f0d680053713b0654bdd5f32a5339cd/protected/humhub/components/behaviors/PolymorphicRelation.php#L70-L70

But the first argument of `static::loadActiveRecord()` must be a string:
https://github.com/humhub/humhub/blob/1db793da1f0d680053713b0654bdd5f32a5339cd/protected/humhub/components/behaviors/PolymorphicRelation.php#L177C50-L177C50

### Additional info

Log:
```
TypeError: humhub\components\behaviors\PolymorphicRelation::loadActiveRecord(): Argument #1 ($className) must be of type string, null given, called in /var/www/humhub/protected/humhub/components/behaviors/PolymorphicRelation.php on line 69 and defined in /var/www/humhub/protected/humhub/components/behaviors/PolymorphicRelation.php:177
Stack trace:
#0 /var/www/humhub/protected/humhub/components/behaviors/PolymorphicRelation.php(69): humhub\components\behaviors\PolymorphicRelation::loadActiveRecord(NULL, NULL)
#1 [internal function]: humhub\components\behaviors\PolymorphicRelation->getPolymorphicRelation()
#2 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Component.php(297): call_user_func_array(Array, Array)
#3 /var/www/humhub/protected/humhub/modules/notification/models/Notification.php(130): yii\base\Component->__call('getPolymorphicR...', Array)
#4 /var/www/humhub/protected/humhub/modules/notification/controllers/ListController.php(46): humhub\modules\notification\models\Notification->getBaseModel()
#5 [internal function]: humhub\modules\notification\controllers\ListController->actionIndex()
#6 /var/www/humhub/protected/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#7 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Controller.php(178): yii\base\InlineAction->runWithParams(Array)
#8 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Module.php(552): yii\base\Controller->runAction('', Array)
#9 /var/www/humhub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('notification/li...', Array)
#10 /var/www/humhub/protected/vendor/yiisoft/yii2/base/Application.php(384): yii\web\Application->handleRequest(Object(humhub\components\Request))
#11 /var/www/humhub/index.php(28): yii\base\Application->run()
#12 {main}
```

| Q                | A
| ---------------- | ---
| HumHub version   | 1.16.0
| PHP version      | 8.2

### PR DESCRIPTION
**Pull request by martin-rueegg**
- Fix #6772
- Regression #6587

### What kind of change does this PR introduce?

- Bugfix

### Does this PR introduce a breaking change?

- No

### The PR fulfills these requirements

- [x] It's submitted to the `develop` branch, _not_ the `master` branch if no hotfix
- [x] When resolving a specific issue, it's referenced in the PR's description (e.g. `Fix #xxx[,#xxx]`, where "xxx" is the Github issue number)
- [ ] All tests [tests](#issuecomment-new) are passing
- [ ] New/updated tests are included
- [x] Changelog was modified

**Other information:**

### CODE REVIEW

**Comment by martin-rueegg** [comment]
Regression from https://github.com/humhub/humhub/commit/428c7a3ac58a9942fa816769134e3b685cfb29bc#diff-63b6b65bbd93ed9d3bb6f24c5ede589d08cf030f8887b055599815653bb4697bR153
- #6587

File: protected/humhub/components/behaviors/PolymorphicRelation.php [hunk 1]
```diff
@@ -169,14 +169,14 @@ private function validateUnderlyingObjectType(?object $object)
...
      * Loads an active record based on classname and primary key.
      *
-     * @param string $className
+     * @param string|mixed $className
      * @param string|int $primaryKey
      *
      * @return null|ActiveRecord|ActiveRecordInterface
      */
-    public static function loadActiveRecord(string $className, $primaryKey): ?ActiveRecordInterface
+    public static function loadActiveRecord($className, $primaryKey): ?ActiveRecordInterface
```
Comment (luke-) [inline protected/humhub/components/behaviors/PolymorphicRelation.php:177]: Would this be also an option? This would allow us to remove the `is_string` check.

```suggestion
    public static function loadActiveRecord(?string $className, $primaryKey): ?ActiveRecordInterface
```

File: protected/humhub/components/behaviors/PolymorphicRelation.php [hunk 2]
```diff
@@ -169,14 +169,14 @@ private function validateUnderlyingObjectType(?object $object)
...
     {
-        if (empty($className) || empty($primaryKey)) {
+        if (($primaryKey !== 0 && empty($primaryKey)) || !is_string($className) || trim($className) === '') {
```
Comment (luke-) [inline protected/humhub/components/behaviors/PolymorphicRelation.php:179]: I would actually prefer the previous variant here for reasons of readability.

Not sure we need to consider a PK with ID 0 or the string of spaces.  Or do you see a specific reason for this?

**Review by luke- — CHANGES_REQUESTED** [review]
@martin-rueegg Thanks for the quick fix.

File: protected/humhub/components/behaviors/PolymorphicRelation.php (hunk 1 above)
Comment (martin-rueegg) [reply protected/humhub/components/behaviors/PolymorphicRelation.php:177]: We can try. There is no restriction on the `getAttribute()` method. In fact, in some cases, objects are returned. This would lead to a fatal error again. So I wanted to be on the safe side. But happy to apply `?string` ...

File: protected/humhub/components/behaviors/PolymorphicRelation.php (hunk 2 above)
Comment (martin-rueegg) [reply protected/humhub/components/behaviors/PolymorphicRelation.php:179]: `0` is a valid primary key. I know that in most places you use `empty()`-checks, but I think that should be avoided.

The `trim()` is not required, of course. Happy to remove.

Comment (luke-) [reply protected/humhub/components/behaviors/PolymorphicRelation.php:179]: You are right, it is a valid PK, but normally there are no situations in which this PK is assigned. e.g. `auto_increment` starts with 1.

I want to keep the codebase as consistent and simple as possible - so I don't want to implement an extra check for `0` here. If it becomes necessary to allow 0, we need to do changes in more places.

File: protected/humhub/components/behaviors/PolymorphicRelation.php (hunk 1 above)
Comment (luke-) [reply protected/humhub/components/behaviors/PolymorphicRelation.php:177]: Thank you, being on the safe side is usually a good thing :-)

But let's risk it here.

**Review by luke- — APPROVED** [review]
