### PR TITLE
Fix #4715: Call to `Content::canArchive()` throws error on global content

### LINKED ISSUE #4715: Content::canArchive() broken on global content
Calling `$content->canArchive()` on a global content fails, duo to:

```
public function canArchive()
{
   return $this->getContainer()->permissionManager->can(new ManageContent());
}
```

This for example happens when generating archive links for global custom page wall entries.

### PR DESCRIPTION
**Pull request by buddh4**
Fixes: https://github.com/humhub/humhub/issues/4715

**What kind of change does this PR introduce?** (check at least one)

- [x] Bugfix

**Does this PR introduce a breaking change?** (check one)

- [x] No

### CODE REVIEW

File: protected/humhub/modules/content/models/Content.php [hunk 1]
```diff
@@ -409,6 +409,16 @@ public function isArchived()
      */
     public function canArchive()
     {
+        // Currently global content can not be archived
+        if(!$this->contentcontainer_id) {
+            return false;
+        }
+
+        // No need to archive content on an archived container, content is marked as archived already
+        if($this->content->content->getContainer()->isArchived()) {
```
Comment (luke-) [inline protected/humhub/modules/content/models/Content.php:418]: @buddh4 Can you please check your codestyle settings in the IDE? Actually, there should be a whitespace after the `if`.

**Review by luke- — CHANGES_REQUESTED** [review]

File: protected/humhub/modules/content/models/Content.php (hunk 1 above)
Comment (buddh4) [reply protected/humhub/modules/content/models/Content.php]: Not an issue with the ide, just did not auto format. Not really used to the space after such blocks.

**Review by luke- — APPROVED** [review]
